#ifndef KEYWORD_H
#define KEYWORD_H

// Keyword classes selected by take_keyword. A token is consumed only when its
// class overlaps the requested mask, so a mnemonic scan will not eat a directive.
enum {
  KW_CLASS_PSEUDO = 1,
  KW_CLASS_MNEMONIC = 2,
  KW_CLASS_DIRECTIVE = 4
};

// Identifiers for every pseudo-op, mnemonic, and directive the assembler recognizes.
enum KeywordId {
  KW_NONE = 0,
  KW_NOP,
  KW_RET,
  KW_PUSH,
  KW_POP,
  KW_PSHW,
  KW_POPW,
  KW_PSHD,
  KW_POPD,
  KW_PSHB,
  KW_POPB,
  KW_MOVI,
  KW_MOV,
  KW_CALL,
  KW_AND,
  KW_NAND,
  KW_OR,
  KW_NOR,
  KW_XOR,
  KW_XNOR,
  KW_NOT,
  KW_LSL,
  KW_LSR,
  KW_ASR,
  KW_ROTL,
  KW_ROTR,
  KW_LSLC,
  KW_LSRC,
  KW_ADD,
  KW_ADDC,
  KW_SUB,
  KW_SUBB,
  KW_CMP,
  KW_SXTB,
  KW_SXTD,
  KW_TNCB,
  KW_TNCD,
  KW_LUI,
  KW_SWA,
  KW_LWA,
  KW_SW,
  KW_LW,
  KW_SDA,
  KW_LDA,
  KW_SD,
  KW_LD,
  KW_SBA,
  KW_LBA,
  KW_SB,
  KW_LB,
  KW_BR,
  KW_BZ,
  KW_BNZ,
  KW_BS,
  KW_BNS,
  KW_BC,
  KW_BNC,
  KW_BO,
  KW_BNO,
  KW_BPS,
  KW_BNPS,
  KW_BG,
  KW_BGE,
  KW_BL,
  KW_BLE,
  KW_BA,
  KW_BAE,
  KW_BB,
  KW_BBE,
  KW_BRA,
  KW_BZA,
  KW_BNZA,
  KW_BSA,
  KW_BNSA,
  KW_BCA,
  KW_BNCA,
  KW_BOA,
  KW_BNOA,
  KW_BPA,
  KW_BNPA,
  KW_BGA,
  KW_BGEA,
  KW_BLA,
  KW_BLEA,
  KW_BAA,
  KW_BAEA,
  KW_BBA,
  KW_BBEA,
  KW_JMP,
  KW_ADPC,
  KW_TRAP,
  KW_FADA,
  KW_FAD,
  KW_SWPA,
  KW_SWP,
  KW_TLBR,
  KW_TLBW,
  KW_TLBI,
  KW_TLBC,
  KW_CRMV,
  KW_MODE,
  KW_RFE,
  KW_IPI,
  KW_EOI,
  KW_MOVU,
  KW_MOVL,
  KW_DIR_GLOBAL,
  KW_DIR_ORIGIN,
  KW_DIR_TEXT,
  KW_DIR_RODATA,
  KW_DIR_DATA,
  KW_DIR_BSS,
  KW_DIR_TEXT_LOAD,
  KW_DIR_RODATA_LOAD,
  KW_DIR_DATA_LOAD,
  KW_DIR_BSS_LOAD,
  KW_DIR_FILL,
  KW_DIR_FILD,
  KW_DIR_FILB,
  KW_DIR_SPACE,
  KW_DIR_ALIGN,
  KW_DIR_DEFINE,
  KW_DIR_LINE,
  KW_DIR_LOCAL,
  KW_COUNT  // number of ids; sizes per-keyword tables
};

// If the token at `current` is a keyword in `class_mask`, consume it and return its id.
// Otherwise leave `current` unchanged and return KW_NONE.
// `current` must address assembler source. Matching uses the same token boundary
// rules as consume_keyword: the previous byte is not an identifier character, and
// the following byte is whitespace, NUL, comma, semicolon, or colon.
enum KeywordId take_keyword(unsigned class_mask);

#endif
